# Generated by Django 5.2.6 on 2025-09-30 09:17

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailmedia", "0005_alter_media_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaRendition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("format_spec", models.JSONField()),
                ("file", models.FileField(upload_to="media", verbose_name="file")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renditions",
                        to="wagtailmedia.media",
                    ),
                ),
            ],
        ),
    ]
