# Generated by Django 5.2.6 on 2025-10-07 19:22

import django.db.models.deletion

from django.db import migrations, models

from wagtailmedia.settings import wagtailmedia_settings


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailmedia", "0006_mediarendition"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaTranscodingJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("backend", models.CharField(max_length=255)),
                ("job_id", models.CharField(max_length=255, unique=True)),
                ("format_spec", models.JSONField()),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=wagtailmedia_settings.MEDIA_MODEL,
                    ),
                ),
                (
                    "rendition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=wagtailmedia_settings.MEDIA_RENDITION_MODEL,
                    ),
                ),
            ],
        ),
    ]
