# Generated by Django 5.2.6 on 2025-10-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailmedia", "0007_mediatranscodingjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediatranscodingjob",
            name="format_spec",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
