# Generated by Django 5.2.6 on 2025-10-23 16:44

import django.core.validators
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailmedia", "0009_alter_mediatranscodingjob_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediarendition",
            name="format_spec",
        ),
        migrations.RemoveField(
            model_name="mediatranscodingjob",
            name="rendition",
        ),
        migrations.AddField(
            model_name="mediarendition",
            name="bitrate",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediarendition",
            name="duration",
            field=models.FloatField(
                blank=True,
                default=0,
                help_text="Duration in seconds",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="duration",
            ),
        ),
        migrations.AddField(
            model_name="mediarendition",
            name="height",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="height"
            ),
        ),
        migrations.AddField(
            model_name="mediarendition",
            name="transcoding_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renditions",
                to="wagtailmedia.mediatranscodingjob",
            ),
        ),
        migrations.AddField(
            model_name="mediarendition",
            name="width",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="width"
            ),
        ),
    ]
