# Generated by Django 5.2.6 on 2026-02-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailmedia", "0010_remove_mediarendition_format_spec_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediatranscodingjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("submitted", "Submitted"),
                    ("progressing", "Progressing"),
                    ("finalising", "Finalising"),
                    ("complete", "Complete"),
                    ("canceled", "Canceled"),
                    ("error", "Error"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
