from django.conf import settings


AWS_MEDIACONVERT_STORAGE_BUCKET_NAME = getattr(
    settings,
    "AWS_MEDIACONVERT_STORAGE_BUCKET_NAME",
    getattr(settings, "AWS_STORAGE_BUCKET_NAME", None),
)
AWS_MEDIACONVERT_ROLE_NAME = getattr(
    settings, "AWS_MEDIACONVERT_ROLE_NAME", "MediaConvert_Default_Role"
)
AWS_MEDIACONVERT_QUEUE_NAME = getattr(
    settings, "AWS_MEDIACONVERT_QUEUE_NAME", "Default"
)
AWS_MEDIACONVERT_ACCESS_KEY_ID = getattr(settings, "AWS_MEDIACONVERT_ACCESS_KEY_ID", "")
AWS_MEDIACONVERT_SECRET_ACCESS_KEY = getattr(
    settings, "AWS_MEDIACONVERT_SECRET_ACCESS_KEY", ""
)
AWS_MEDIACONVERT_REGION_NAME = getattr(settings, "AWS_MEDIACONVERT_REGION_NAME", "")
